/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicacifrado;

import javax.swing.JOptionPane;

/**
 *
 * @author Dramirez
 */
public class Ventana extends javax.swing.JFrame {
    public static String mayuscula = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public static String minuscula = "abcdefghijklmnopqrstuvwxyz";
    
    
    public static String descifradoCesar(String texto, int desplazamiento) {        
        String salida = "";		
        int aux = mayuscula.length();
        int posicion;
        int nuevaPosicion;

        texto = texto.toUpperCase();

        for (char caracter : texto.toCharArray()) {
            if (caracter == ' ' || caracter == '.' || caracter == ','  || caracter == '\n') {
                salida += caracter;
                continue;
            }
            posicion = caracter - mayuscula.charAt(0);
            nuevaPosicion = Math.floorMod(posicion - desplazamiento, aux);
            salida += mayuscula.charAt(nuevaPosicion);
        }
        return salida;
    }
    
    public static String descifradoVigenere(String texto, String clave) {
        String salida = "";
        int aux = mayuscula.length();
        int abecedario = -1;
        int posicionClave, letraEncriptado, letraClave, letraDesencriptada;
        int resta;  
        
        for (char caracter : texto.toCharArray()) {
            if (caracter == ' ' || caracter == '.' || caracter == ','  || caracter == '\n') {
                salida += caracter;
                continue;
            } 
            abecedario++;
            posicionClave = abecedario % clave.length();
            letraEncriptado = caracter - mayuscula.charAt(0);
            letraClave = clave.charAt(posicionClave) - mayuscula.charAt(0);
            resta = letraEncriptado - letraClave;
            if (resta >= 0) {
                letraDesencriptada = resta % aux;  
            } else {
                letraDesencriptada = (resta + aux) % aux;
            }
            salida += mayuscula.charAt(letraDesencriptada);
        }
        return salida;
    }
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaCifrado = new javax.swing.JLabel();
        botonCesar = new javax.swing.JButton();
        botonVigenere = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoCifrado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescifrado = new javax.swing.JTextArea();
        etiquetaDescifrado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos de cifrado");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaCifrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaCifrado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCifrado.setText("Texto cifrado");
        panel.add(etiquetaCifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        botonCesar.setText("Cesar");
        botonCesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCesarActionPerformed(evt);
            }
        });
        panel.add(botonCesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 80, -1));

        botonVigenere.setText("Vigenere");
        botonVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVigenereActionPerformed(evt);
            }
        });
        panel.add(botonVigenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 80, -1));

        campoCifrado.setColumns(20);
        campoCifrado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        campoCifrado.setLineWrap(true);
        campoCifrado.setRows(5);
        jScrollPane1.setViewportView(campoCifrado);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 200));

        campoDescifrado.setColumns(20);
        campoDescifrado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        campoDescifrado.setLineWrap(true);
        campoDescifrado.setRows(5);
        jScrollPane2.setViewportView(campoDescifrado);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 240, 160));

        etiquetaDescifrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaDescifrado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaDescifrado.setText("Texto descifrado");
        panel.add(etiquetaDescifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione una opción");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 50));

        campoClave.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        panel.add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clave:");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 20));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCesarActionPerformed
        if(!campoClave.getText().isEmpty()){
            int clave = Integer.parseInt(campoClave.getText());
            String texto = descifradoCesar(campoCifrado.getText(), clave);
            campoDescifrado.setText(texto);
        }else{
            JOptionPane.showMessageDialog(null,"El campo de entrada no puede ser nulo");
        }
    }//GEN-LAST:event_botonCesarActionPerformed

    private void botonVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVigenereActionPerformed
        if(!campoCifrado.getText().isEmpty()){
            String desencriptado = descifradoVigenere(campoCifrado.getText(), campoClave.getText());
            campoDescifrado.setText(desencriptado);
        }else{
            JOptionPane.showMessageDialog(null,"El campo de entrada no puede ser nulo");
        }
    }//GEN-LAST:event_botonVigenereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCesar;
    private javax.swing.JButton botonVigenere;
    private javax.swing.JTextArea campoCifrado;
    private javax.swing.JTextField campoClave;
    private javax.swing.JTextArea campoDescifrado;
    private javax.swing.JLabel etiquetaCifrado;
    private javax.swing.JLabel etiquetaDescifrado;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}

